package com.guisedoc.enums;

public enum ErrorType {
	
	SUCCESS, DATABASE_CONNECTION, DATABASE_QUERY, INVALID_LOGIN,
	NONE_FOUND, USER_NOT_EXISTING, NOTHING_TO_DELETE, NOTHING_TO_UPDATE,
	USER_ALREADY_EXISTS, FAILURE
	

}
